### ISSUE TITLE
Roll up for preact-redux-todo?

### ISSUE THREAD

**Issue by katopz** [fdaciuk/preact-playground#10]
Is it possible to rollup preact-redux-todo?
Here far as I try and get stuck.

```
Module D:\labs\preact-react-redux-playground\preact-redux-todo\node_modules\react\react.js does not export Component (imported by D:\labs\preact-react-redux-playground\preact-redux-todo\src\components\app.js)
```

Why [preact-redux](https://github.com/fdaciuk/preact-react-redux-playground/blob/master/preact-redux%2Fwebpack.config.js#L43) need `preact-compat`?

Why [preact-redux-todo](https://github.com/fdaciuk/preact-react-redux-playground/blob/master/preact-redux-todo%2Fwebpack.config.js#L43) no need `preact-compat`?

Thanks

**Comment by fdaciuk** [comment]
I didn't try it yet. But I prefer JSPM or webpack instead rollup =)
